### PR TITLE
[CSM-249] Apply new wallet names convention

### PR DESCRIPTION
**Pull request by Martoon-00**
Switches from `wallet set -> wallet -> account` to `wallet -> account -> address` model

### CODE REVIEW

**Comment by Martoon-00** [comment]
Backend part also required modification

**Comment by akegalj** [comment]
@Martoon-00 
> Backend part also required modification

backend part docs is generated with swagger

**Comment by Martoon-00** [comment]
Um, not backend, I mean https://cardanodocs.com/technical/hd-wallets/

**Comment by akegalj** [comment]
@Martoon-00 yes, that has to be updated as well :/

**Comment by Martoon-00** [comment]
Ready. Please merge if there are no objections

**Pull request merged**
