### PR TITLE
Improve hd-wallets

### PR DESCRIPTION
**Pull request by jonathancross**
I did my best here (based on my understanding of Bitcoin HD wallets), but there were some sentences which didn't make sense to me.  Feel free to suggest corrections or we can wait and do a follow up PR with more improvements.

In the future, we might want to consider using terms more uniformly from BIP-32 and removing parts of this which just repeat portions of that spec so it is clear what is unique about Cardano.

### CODE REVIEW

**Comment by jonathancross** [comment]
Friendly ping @jonnysmillie

**Comment by jonnysmillie** [comment]
Hi @jonathancross, thanks for your contribution. Unfortunately I cannot approve content changes to this documentation. You should seek a review from @denisshevchenko.

**Comment by jonathancross** [comment]
Thanks @jonnysmillie , would still appreciate a review from you.
@denisshevchenko : any issues here?
Or perhaps @jonnysmillie , @KtorZ or @h0rhay can help out?

**Comment by KtorZ** [comment]
@denisshevchenko is indeed working on improving this doc (from cardano-sl though) if I recall correctly. Might be nice for you two to sync!

Thanks!

**Comment by jonathancross** [comment]
Thanks @KtorZ , unfortunatly it looks like @denisshevchenko might be on vacation or something.
I see that @edsko recently reviewed his documentation PR, maybe he can help out here?

**Comment by edsko** [comment]
I don't have github privileges to formally review this, but these seem to be stylistic corrections only, looks fine to me.

**Comment by jonathancross** [comment]
Thanks @edsko -- anyone can review a PR, even if you cannot merge.  Having an approval helps others establish merge-worthiness (regardless of your status within this particular project).

**Review by edsko — APPROVED** [review]
LGTM.

**Comment by edsko** [comment]
Ah, quite. I thought I couldn't as I could add myself as a reviewer :)

**Comment by jonathancross** [comment]
Thanks for merging @KtorZ.
I'd consider contributing more, but probably not if simple PRs take 5 months for approval.
Are further contributions welcome?

**Comment by KtorZ** [comment]
@jonathancross 
My apologizes for the delay, I hadn't write access on the repo until recently so couldn't really do anything. I do now.

Contributions are highly welcome :)
Thanks again!

**Pull request merged**
